### ISSUE TITLE
ValueError: Cannot feed value of shape (1, 720, 1280, 4) for Tensor 'input_image:0', which has shape '(1, None, None, 3)'

### ISSUE THREAD

**Issue by leopku** [wangsrGit119/cartoon-media#1]
Result as no image and '加载失败'

API `/image-upload/` returned as below

```json
{"status":200,"base64":null}
```

**Comment by wangsrGit119** [comment]
Mac?
 here ,
> question: https://forum.image.sc/t/error-when-evaluating-my-dlc-trained-network-valueerror-cannot-feed-value-of-shape-1-720-1280-4-for-tensor-placeholder-0-which-has-shape-1-none-none-3/62669 ;
> fixed: https://github.com/DeepLabCut/DeepLabCut/issues/1608

**Comment by leopku** [comment]
Docker inside.
Docker host platform was linux.

**Comment by wangsrGit119** [comment]
> Docker inside. Docker host platform was linux.

now ok,you can pull latest code, reason: image shape compression ,   your image is 4,but input image constraint is 3. i modify that.
other , if you want to watch more than 
```
print (np.shape(image))
```

**Comment by leopku** [comment]
Thanks a lot.
I'll review it after Spring Festival.

**Comment by leopku** [comment]
Verified.
Thank you and happy new year.
